- name: copy mongodb repo file
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/

- name: Install mongodb
  yum:
    name: mongodb-org
    state: present

- name: Update mongodb configuration file from listening on 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
