- name: copy mongodb repo file
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/

- name: Install mongodb
  yum:
    name: mongodb-org
    state: present

- name: Update mongodb configuration file from listening on 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB Service
  systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download {{APP}} Schema
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
    EXTRACT_DIR: /tmp/mongodb
    APP_USER: root

- name: Load Schema
  shell: mongo < {{item}}
  loop:
    - catalogue.js
    - users.js
  args:
    chdir: /tmp/mongodb/mongodb-main