- name: Demo on play variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
       debug:
         msg: URl = {{ URL }}

- name: Demo on play variables
  hosts: all
  tasks:
    - name: Print URL
        debug:
          msg: URl = {{ URL }}
        vars:
          URL: play.example.com
