- name: Setup Roboshop Project
  hosts: all
  become: yes
  roles:
    - name: Import Frontend
      ansible.builtin.import_role:
        name: frontend
    - name: Import Catalogue
      ansible.builtin.import_role:
        name: catalogue
