- name: Setup Roboshop Project
  hosts: all
  become: yes
  tasks:
    - name: Import Frontend
      ansible.builtin.import_role:
        name: frontend
      tags:
        - frontend
      when: APP == "frontend"

    - name: Import Catalogue
      ansible.builtin.import_role:
        name: catalogue
      tags:
        - catalogue
      when: APP == "catalogue"

    - name: Import Mongodb
      ansible.builtin.import_role:
        name: mongodb
      tags:
        - mongodb
      when: APP == "mongodb"

    - name: Import Redis
      ansible.builtin.import_role:
        name: redis
      tags:
        - redis
      when: APP == "redis"