- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Html Docs
  file:
    path: /usr/share/nginx/html
    state: absent

##### This is download from Git repo directly
- name: Download {{ COMPONENT }} Component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    EXTRACT_DIR: /usr/share/nginx
    APP_USER: root
    #COMPONENT_DIR: /usr/share/nginx/html

- name: Copy Nginx Config file
  template:
    src: roboshop.conf
    dest:/etc/nginx/default.d/roboshop.conf

- name: Restart service nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

