- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Html Docs
  file:
    path: /usr/share/nginx/html
    state: absent

- name: Download {{COMPONENT}} from GitHub
  include_role:
    name: common
    tasks_from: download-github

- name: Restart service nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes