- name: Setup nodejs for {{ COMPONENT }} Component
  include_role:
    name: common
    tasks_from: nodejs
  vars:
    URL: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"

- name: Import NodeJS Tasks
  include_role:
    name: common
    tasks_from: nodejs



