- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: directory
    mode: '0755'

- name: Download {{ APP }} Component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    EXTRACT_DIR: /home/roboshop/catalogue
    APP_USER: roboshop

- name: change the directory
  shell: cd /home/roboshop/catalogue

- name: Install Nodejs modules
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

#NOTE: We need to update the IP address of MONGODB Server in systemd.service file

- name: Update SystemD script for Catalogue Service
  ansible.builtin.replace:
    path: /home/roboshop/catalogue/systemd.service
    regexp: 'MONGO_DNSNAME'
    replace: "mongodb-{{ENV}}.srinivassuryapet.ml"

- name: Setup SystemD script
  shell: mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes





  # systemctl daemon-reload
  # systemctl start catalogue
  # systemctl enable catalogue



