- name: Download {{ COMPONENT }} Component
  #ansible.builtin.get_url:
  get_url:
    url: "{{URL}}"
    dest: /tmp/{{COMPONENT}}.zip

- name: Remove old content
  #ansible.builtin.file:
  file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: Create directory for {{ COMPONENT }} component
  ansible.builtin.file:
    path: "{{EXTRACT_DIR}}"
    state: directory
  become_user: "{{APP_USER}}"

- name: Unarchive {{ COMPONENT }} Component
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes
  become_user: "{{APP_USER}}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    mode: '0755'
  when: COMPONENT == "frontend"

- name: Move Htdocs Directory
  shell: mv /usr/share/nginx/frontend-main/static/* /usr/share/nginx/html/.
  when: COMPONENT == "frontend"

- name: Move localhost.conf
  shell: mv /usr/share/nginx/frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf
  when: COMPONENT == "frontend"
