- name: Download {{ COMPONENT }} component
  ansible.builtin.get_url:
    url: "{{URL}}"
    dest: /tmp/{{COMPONENT}}.zip

- name: Remove old content
  ansible.builtin.file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: Create directory for {{ COMPONENT }} component
  ansible.builtin.file:
    path: "{{EXTRACT_DIR}}"
    state: directory
  become_user: "{{APP_USER}}"

- name: Unarchive {{ COMPONENT }} Component
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes
  become_user: "{{APP_USER}}"

- name: Move Htdocs Directory
  ansible.builtin.shell: mv /usr/share/nginx/html/frontend-main/static/* /usr/share/nginx/html/.
  when: COMPONENT == "frontend"

- name: Move Htdocs Directory
  ansible.builtin.shell: mv /usr/share/nginx/html/frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf
  when: COMPONENT == "frontend"

- name: Move catalogue Directory
  ansible.builtin.shell: mv /home/roboshop/catalogue/catalogue-main/* /home/roboshop/catalogue/.
  when: COMPONENT == "catalogue"
  become_user: "{{APP_USER}}"

- name: Move user Directory
  ansible.builtin.shell: mv /home/roboshop/user/user-main/* /home/roboshop/user/.
  when: COMPONENT == "user"
  become_user: "{{APP_USER}}"

- name: Move cart Directory
  ansible.builtin.shell: mv /home/roboshop/cart/cart-main/* /home/roboshop/cart/.
  when: COMPONENT == "cart"
  become_user: "{{APP_USER}}"
