- name: Download & Extract {{COMPONENT}}
  unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy the extracted contect
  copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes
