- name: sethostname for {{COMPONENT}} component
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Disable autoshutdown for {{COMPONENT}} component
  ansible.builtin.shell: disable-auto-shutdown

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
  when: COMPONENT == "catalogue" or COMPONENT == "user" or COMPONENT == "cart" or COMPONENT == "shipping" or COMPONENT == "payment"
  register: out

- name: Grab UID and GID of Roboshop user
  when: COMPONENT == "catalogue" or COMPONENT == "user" or COMPONENT == "cart" or COMPONENT == "shipping" or COMPONENT == "payment"
  set_fact:
    RS_UID: "{{out.uid}}"
    RS_GID: "{{out.group}}"