- name: sethostname for {{COMPONENT}} component
  shell: set-hostname {{COMPONENT}}

- name: Disable autoshutdown for {{COMPONENT}} component
  shell: disable-auto-shutdown

- name: Add roboshop user
  user:
    name: roboshop
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"