- name: Install Nodejs
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download {{ COMPONENT }} Component
  include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{COMPONENT}}/
    APP_USER: roboshop

- name: Install NodeJS Modules
  npm:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}-main/
  become_user: roboshop

- name: Download {{ COMPONENT }} Component
  include_tasks: systemd.yml