- name: Install Python3
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: Download {{ COMPONENT }} Component
  include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{COMPONENT}}/
    APP_USER: roboshop

- name: Install Python requirements
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}-main/requirements.txt
    executable: pip3

- name: Update User ID in Payment configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}-main/payment.ini
    regexp: "^uid"
    line: "uid={{RS_UID}}"

- name: Update Group Id in Payment configuration
  ansible.builtin.lineinfile:
   path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}-main/payment.ini
   regexp: "^gid"
   line: "gid={{RS_GID}}"

- name: Download {{ COMPONENT }} Component
  include_tasks: systemd.yml