#- name: Setup nodejs for {{ COMPONENT }} Component
#  include_role:
#    name: common
#    tasks_from: nodejs
#  vars:
#      URL: "https://github.com/roboshop-devops-project/cart/archive/main.zip"
- name: OS Pre-reqs
  include_role:
    name: common
    tasks_from: os-prereqs

- name: Import NodeJS Tasks
  include_role:
    name: common
    tasks_from: nodejs
